# Generated by Django 5.1.7 on 2025-04-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
