# Generated by Django 5.1.6 on 2025-02-17 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table='task_table',
        ),
    ]
