# Generated by Django 5.1.7 on 2025-03-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_testattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='user_answers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
