# Generated by Django 5.1.7 on 2025-04-17 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_emailotp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testattempt',
            unique_together={('quiz', 'email')},
        ),
    ]
