# Generated by Django 5.1.6 on 2025-02-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_text_comment_content_remove_post_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
