# Generated by Django 5.1.7 on 2025-04-16 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_group_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriber',
            unique_together={('email', 'group')},
        ),
    ]
