# Generated by Django 5.1.7 on 2025-04-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='video',
        ),
        migrations.AddField(
            model_name='module',
            name='video_url',
            field=models.URLField(default=None, help_text='Paste YouTube or video URL'),
            preserve_default=False,
        ),
    ]
